/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c1exchangegen.gui;

import java.awt.HeadlessException;
import javax.swing.tree.TreeModel;
import org.pushingpixels.substance.api.SubstanceConstants;
import org.pushingpixels.substance.api.SubstanceLookAndFeel;

/**
 *
 * @author psyriccio
 */
public class ConfigurationForm extends javax.swing.JFrame {

    /**
     * Creates new form ConfigurationForm
     */
    public ConfigurationForm() {
        initComponents(); 
    }

    public void setModels(TreeModel modelIn, TreeModel modelOut, TreeModel modelRes) {
        if(modelIn != null) { 
            this.jConfTree1.putClientProperty(SubstanceLookAndFeel.FOCUS_KIND, SubstanceConstants.FocusKind.NONE);
            this.jConfTree1.putClientProperty(SubstanceLookAndFeel.TREE_SMART_SCROLL_ANIMATION_KIND, false);
            jConfTree1.setModel(modelIn);
        }
        if(modelOut != null) {
            this.jConfTree2.putClientProperty(SubstanceLookAndFeel.FOCUS_KIND, SubstanceConstants.FocusKind.NONE);
            this.jConfTree2.putClientProperty(SubstanceLookAndFeel.TREE_SMART_SCROLL_ANIMATION_KIND, false);
            jConfTree2.setModel(modelOut);
        }
        if(modelRes != null) {
            this.jTreeResult.putClientProperty(SubstanceLookAndFeel.FOCUS_KIND, SubstanceConstants.FocusKind.NONE);
            this.jTreeResult.putClientProperty(SubstanceLookAndFeel.TREE_SMART_SCROLL_ANIMATION_KIND, false);
            jTreeResult.setModel(modelRes);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBarMain = new javax.swing.JToolBar();
        jSP_Log_Main = new javax.swing.JSplitPane();
        jSP_InOut_Res = new javax.swing.JSplitPane();
        jSP_In_Out = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jConfTree1 = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        jConfTree2 = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTreeResult = new javax.swing.JTree();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("c1ExchangeGen");
        setPreferredSize(new java.awt.Dimension(1600, 800));

        jToolBarMain.setRollover(true);

        jSP_Log_Main.setDividerLocation(600);
        jSP_Log_Main.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSP_Log_Main.setResizeWeight(1.0);
        jSP_Log_Main.setToolTipText("");
        jSP_Log_Main.setContinuousLayout(true);

        jSP_InOut_Res.setDividerLocation(1000);

        jSP_In_Out.setDividerLocation(500);

        jConfTree1.setModel(null);
        jScrollPane2.setViewportView(jConfTree1);

        jSP_In_Out.setLeftComponent(jScrollPane2);

        jConfTree2.setModel(null);
        jConfTree2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jConfTree2);
        jConfTree2.getAccessibleContext().setAccessibleName("jTree");

        jSP_In_Out.setRightComponent(jScrollPane1);

        jSP_InOut_Res.setLeftComponent(jSP_In_Out);

        jTreeResult.setModel(null);
        jTreeResult.setToolTipText("");
        jScrollPane3.setViewportView(jTreeResult);

        jSP_InOut_Res.setRightComponent(jScrollPane3);

        jSP_Log_Main.setTopComponent(jSP_InOut_Res);

        jTextPane1.setEditable(false);
        jTextPane1.setName(""); // NOI18N
        jTextPane1.setPreferredSize(new java.awt.Dimension(100, 100));
        jScrollPane4.setViewportView(jTextPane1);

        jSP_Log_Main.setRightComponent(jScrollPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1490, Short.MAX_VALUE))
            .addComponent(jSP_Log_Main)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSP_Log_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree jConfTree1;
    private javax.swing.JTree jConfTree2;
    private javax.swing.JSplitPane jSP_InOut_Res;
    private javax.swing.JSplitPane jSP_In_Out;
    private javax.swing.JSplitPane jSP_Log_Main;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToolBar jToolBarMain;
    private javax.swing.JTree jTreeResult;
    // End of variables declaration//GEN-END:variables
}
