/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c1exchangegen.gui;

import java.awt.HeadlessException;
import javax.swing.tree.TreeModel;
import org.pushingpixels.substance.api.SubstanceConstants;
import org.pushingpixels.substance.api.SubstanceLookAndFeel;

/**
 *
 * @author psyriccio
 */
public class ConfigurationForm extends javax.swing.JFrame {

    /**
     * Creates new form ConfigurationForm
     */
    public ConfigurationForm() {
        initComponents(); 
    }

    public ConfigurationForm(TreeModel model1, TreeModel model2, TreeModel model3) throws HeadlessException {
        initComponents();
        this.jConfTree1.setModel(model1);
        this.jConfTree1.putClientProperty(SubstanceLookAndFeel.FOCUS_KIND, SubstanceConstants.FocusKind.NONE);
        this.jConfTree1.putClientProperty(SubstanceLookAndFeel.TREE_SMART_SCROLL_ANIMATION_KIND, false);
        this.jConfTree2.setModel(model2);
        this.jConfTree2.putClientProperty(SubstanceLookAndFeel.FOCUS_KIND, SubstanceConstants.FocusKind.NONE);
        this.jConfTree2.putClientProperty(SubstanceLookAndFeel.TREE_SMART_SCROLL_ANIMATION_KIND, false);
        this.jTreeResult.setModel(model3);
        this.jTreeResult.putClientProperty(SubstanceLookAndFeel.FOCUS_KIND, SubstanceConstants.FocusKind.NONE);
        this.jTreeResult.putClientProperty(SubstanceLookAndFeel.TREE_SMART_SCROLL_ANIMATION_KIND, false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jConfTree1 = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        jConfTree2 = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTreeResult = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jSplitPane2.setDividerLocation(600);
        jSplitPane2.setResizeWeight(0.7);

        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setResizeWeight(0.3);

        jConfTree1.setModel(null);
        jScrollPane2.setViewportView(jConfTree1);

        jSplitPane1.setLeftComponent(jScrollPane2);

        jConfTree2.setModel(null);
        jScrollPane1.setViewportView(jConfTree2);
        jConfTree2.getAccessibleContext().setAccessibleName("jTree");

        jSplitPane1.setRightComponent(jScrollPane1);

        jSplitPane2.setLeftComponent(jSplitPane1);

        jTreeResult.setToolTipText("");
        jScrollPane3.setViewportView(jTreeResult);

        jSplitPane2.setRightComponent(jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree jConfTree1;
    private javax.swing.JTree jConfTree2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTree jTreeResult;
    // End of variables declaration//GEN-END:variables
}
